# Generated by Django 2.2 on 2019-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191213_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text description intended for demonstration purpose only'),
            preserve_default=False,
        ),
    ]
